schema_version: 1

# 固定正式 release 依赖仓库的源码版本。
# 只有当对应仓库内容确实变更时，才需要更新这里的 ref。
dependencies:
  chains_dev_jars:
    repository: Java-Chains/chains-dev-jars
    ref: 7e5a0b57126a31750c52b9ba09580ae63a3e8f0f

  java_echo_generator:
    repository: Java-Chains/java-echo-generator
    ref: a5dd7275d50a1f08328d12bd2373ed5d8fe8cc78

  java_memshell_generator:
    repository: Java-Chains/java-memshell-generator
    ref: 965c630fa288fd7954dcf68009481d45d5cd81c8

  java_chains_front:
    repository: Java-Chains/java-chains-front
    ref: 1c1d4cbf3c969b2b32905baeae7ce3b605b4d573

  chains_config:
    repository: Java-Chains/chains-config
    ref: c9e027059f82c37df0e026bd190499d2ddc7b223
